(() => {
  'use strict';
  const panel=document.getElementById('prr-panel'),agency=document.getElementById('prr-agency'),gap=document.getElementById('prr-gap'),draft=document.getElementById('prr-draft'),email=document.getElementById('prr-email'),ack=document.getElementById('prr-ack'),submit=document.getElementById('prr-submit'),state=document.getElementById('prr-submit-state'),life=document.getElementById('prr-lifecycle'),lifeStatus=document.getElementById('prr-lifecycle-status'),lifeDetail=document.getElementById('prr-lifecycle-detail');const es=()=>{try{return localStorage.getItem('tensLanguage')==='es'}catch{return document.documentElement.lang==='es'}};
  let current=null,pollTimer=null;
  const validEmail=v=>/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(String(v||'').trim())&&String(v||'').trim().length<=254;
  function bridgeReady(){return Boolean(window.TENS_PRR_BRIDGE&&typeof window.TENS_PRR_BRIDGE.submit==='function')}
  function sync(){submit.disabled=!current||!ack.checked||!validEmail(email.value)||!bridgeReady();state.textContent=bridgeReady()?(es()?'Introduce el correo donde TENS debe avisarte, revisa la solicitud exacta, confírmala y luego envíala.':'Enter the email where TENS should notify you, review the exact request, acknowledge it, then submit.'):(es()?'El envío está desactivado en esta beta por etapas. No se enviará ninguna solicitud.':'Submission is disabled in this staged beta. No request will be sent.')}
  function stopPoll(){if(pollTimer){clearTimeout(pollTimer);pollTimer=null}}
  async function refreshStatus(requestId){if(!requestId||!window.TENS_PRR_STATUS)return;try{const r=await window.TENS_PRR_STATUS.get(requestId),p=r.publicStatus||{};life.hidden=false;lifeStatus.textContent=p.status||r.state||(es()?'Estado disponible':'Status available');lifeDetail.textContent=p.detail||'';const final=['Ready','Delivered','Dry Run Verified'].includes(String(p.status||''));if(!final){stopPoll();pollTimer=setTimeout(()=>refreshStatus(requestId),10000)}}catch(e){}}
  function render(proposal){stopPoll();current=proposal&&typeof proposal==='object'?proposal:null;ack.checked=false;email.value='';submit.textContent=es()?'Enviar solicitud':'Submit Request';ack.disabled=false;email.disabled=false;life.hidden=true;if(!current){panel.hidden=true;return}agency.textContent=current.agency||'';gap.textContent=current.evidenceGap||'';draft.textContent=current.draft||'';panel.hidden=false;sync()}
  ack.addEventListener('change',sync);email.addEventListener('input',sync);window.addEventListener('tens-prr-bridge-ready',sync);
  submit.addEventListener('click',async()=>{if(!current||!ack.checked||!validEmail(email.value)||!bridgeReady())return sync();submit.disabled=true;state.textContent=es()?'Enviando la solicitud exacta aprobada…':'Submitting exact approved request…';
    try{const r=await window.TENS_PRR_BRIDGE.submit(current,{acknowledged:true,submitted:true,customerEmail:email.value.trim()});state.textContent=r&&r.status?r.status:(es()?'Solicitud enviada.':'Request submitted.');if(r&&r.requestId){refreshStatus(r.requestId)}if(r&&r.providerWritePerformed===false){submit.textContent=es()?'Prueba en seco verificada':'Dry-run verified';submit.disabled=true}else{submit.textContent=es()?'Enviada':'Submitted';ack.disabled=true;email.disabled=true}}
    catch(e){state.textContent=es()?'El envío no se completó. No se envió nada salvo que TENS haya devuelto un recibo de envío.':'Submission was not completed. Nothing was sent unless TENS returned a send receipt.';sync()}
  });
  window.TENS_PRR_UI=Object.freeze({render,bridgeReady,validEmail,refreshStatus});
})();
